/*  =========================================================================
    zpgutil_classes - private header file

    Copyright (c) the Contributors as noted in the AUTHORS file.                                                             
                                                                                                                             
    This Source Code Form is subject to the terms of the GNU General Public License as published by the Free Software Foundat
    ion; either version 3 of the License, or (at your option) any later version.                                             
    See the GNU General Public License for more details                                                                      
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef __ZPGUTIL_CLASSES_H_INCLUDED__
#define __ZPGUTIL_CLASSES_H_INCLUDED__

//  External API
#include "../include/zpgutil.h"

//  Internal API

#endif
